### PR TITLE
Added Bakery Lightmapper light types

### PR DESCRIPTION
**Pull request by arranash**
Added Bakery types, added bakery to assembly definition

### CODE REVIEW

**Comment by arranash** [comment]
This is my first pull request, apologies if I've made mistakes.
I've tested in an empty 2022 VRChat project, it creates no errors when bakery isn't installed and works when bakery is installed.

**Comment by JordoVR** [comment]
recheck

**Comment by JordoVR** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JordoVR** [comment]
I took the liberty of merging the VPM branch as this is the branch we're using moving forward, this looks promising, might add it to 1.4.0 (that coincidentally is Bakery related)

**Review by JordoVR — APPROVED** [review]

**Comment by JordoVR** [comment]
Thank you! Included in 1.4.0 barring no issues while testing! :D

**Pull request merged**
